In [22]:
# Importing Libraries
import pandas as pd

url_2023 = ("https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2023.parquet")
url_2024 = ("https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2024.parquet")
url_2025 = ("https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2025.parquet")
url_2026 = ("https://github.com/nflverse/nflverse-data/releases/download/pbp/play_by_play_2026.parquet")

pbp_2023 = pd.read_parquet(url_2023)
pbp_2024 = pd.read_parquet(url_2024)
pbp_2025 = pd.read_parquet(url_2025)
pbp_2026 = pd.read_parquet(url_2026)

pbp = pd.concat([pbp_2023, pbp_2024, pbp_2025, pbp_2026], ignore_index=True)

pbp.head(15)

Total: 153,590 rows, 372 columns

season
2023    49665
2024    49492
2025    48771
2026     5662
Name: count, dtype: int64

In [27]:
print(f"Total: {pbp.shape[0]:,} rows, {pbp.shape[1]:,} columns")
pbp["season"].value_counts().sort_index()

Total: 153,590 rows, 372 columns

season
2023    49665
2024    49492
2025    48771
2026     5662
Name: count, dtype: int64

In [23]:
pbp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153590 entries, 0 to 153589
Columns: 372 entries, play_id to pass_oe
dtypes: float64(200), int32(7), object(165)
memory usage: 431.8+ MB

In [24]:
pbp.describe()

,play_id,week,yardline_100,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,quarter_end,drive,sp,qtr,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
count,153590.000000,153590.000000,142640.000000,153574.000000,153574.000000,153574.000000,153590.000000,151826.000000,153590.000000,153590.000000,...,153590.000000,153590.000000,151814.000000,51922.000000,51922.000000,51922.000000,51922.000000,51922.000000,116997.000000,113659.000000
mean,2185.547327,9.643219,47.794034,409.148378,803.357684,1704.166415,0.017664,11.317212,0.075415,2.567218,...,0.085995,0.511251,0.006235,0.733994,5.531640,3.705886,0.775653,0.578746,0.628657,-1.420390
std,1273.382577,5.721603,23.934147,282.958165,560.894733,1058.105007,0.131727,6.593157,0.264061,1.129452,...,0.280358,0.499875,1.249240,0.528976,2.564705,2.630400,0.254082,0.356891,0.241043,42.392455
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,-12.689102,-3.181688,0.442673,0.000000,0.026981,0.004220,0.013008,-99.538189
25%,1092.000000,4.000000,30.000000,144.000000,274.000000,781.000000,0.000000,6.000000,0.000000,2.000000,...,0.000000,0.000000,-0.557815,0.325633,3.759033,2.000000,0.555672,0.242655,0.455945,-42.566235
50%,2165.000000,10.000000,49.000000,389.000000,784.000000,1800.000000,0.000000,11.000000,0.000000,2.000000,...,0.000000,1.000000,-0.000000,0.609365,4.623872,3.000000,0.983020,0.474498,0.601310,3.849757
75%,3261.000000,15.000000,68.000000,654.000000,1285.000000,2590.000000,0.000000,17.000000,0.000000,4.000000,...,0.000000,1.000000,0.530561,1.008897,6.928176,5.000000,1.000000,0.999328,0.858976,32.930297
max,5519.000000,22.000000,99.000000,900.000000,1800.000000,3600.000000,1.000000,34.000000,1.000000,5.000000,...,1.000000,1.000000,8.882384,9.585749,23.952005,36.000000,1.000000,1.000000,0.997794,97.848164

In [25]:
#Looking for Missing Values
pbp.isnull().sum()

play_id                     0
game_id                     0
old_game_id                 0
home_team                   0
away_team                   0
                        ...
xyac_median_yardage    101668
xyac_success           101668
xyac_fd                101668
xpass                   36593
pass_oe                 39931
Length: 372, dtype: int64

In [26]:
# Checking for Duplicate Values
print(f"Number of Duplicate Values: {pbp.duplicated().sum()}")

Number of Duplicate Values: 0